server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery: #Nacos注册中心地址
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: cloud_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?serverTimezone=UTC
    username: root
    password: 123999
#    type: com.alibaba.druid.pool.DruidDataSource
feign:
  hystrix:
    enabled: true
    command:
      default:
        circuitBreaker:
          sleepWindowInMilliseconds: 3000
          forceClosed: true
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000
    shareSecurityContext: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mapper/*.xml