server:
  port: 80

spring:
  application:
    name: openfeign-hystrix-consumer-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

feign:
  hystrix:
    enabled: true